import {
  Business,
  Product,
  Order,
  Expense,
  CashRemittance,
  DeliveryZone,
  User,
  DailyProblemNote,
} from "@/types";

export const initialBusinesses: Business[] = [
  {
    id: "biz_gambia",
    name: "Gambia Track Store",
    country: "Gambie",
    currency: "GMD",
    description: "Distribution e-commerce COD Banjul, Serrekunda, Brikama & West Coast",
    active: true,
  },
];

export const initialUsers: User[] = [
  {
    id: "user_mouhamed",
    name: "Mouhamed Konteye",
    email: "mouhamed@gambiatrack.com",
    role: "OWNER_ADMIN",
    phone: "+220 311 4567",
    active: true,
    businessIds: ["biz_gambia"],
  },
  {
    id: "user_partner",
    name: "Associé Gambie (Co-Owner 50%)",
    email: "partner@gambiatrack.com",
    role: "OWNER_ADMIN",
    phone: "+220 334 5678",
    active: true,
    businessIds: ["biz_gambia"],
  },
  {
    id: "user_confirmer_1",
    name: "Fatoumatta Bah",
    email: "fatoumatta@gambiatrack.com",
    role: "CONFIRMATOR",
    phone: "+220 722 3344",
    active: true,
    businessIds: ["biz_gambia"],
  },
  {
    id: "user_rider_gambia",
    name: "Bakary Touray (Livreur Banjul / Kairaba)",
    email: "bakary@gambiatrack.com",
    role: "DELIVERY_AGENT",
    phone: "+220 789 0123",
    active: true,
    businessIds: ["biz_gambia"],
  },
  {
    id: "user_rider_2",
    name: "Ebrima Jallow (Livreur Brikama / Sukuta)",
    email: "ebrima@gambiatrack.com",
    role: "DELIVERY_AGENT",
    phone: "+220 901 2345",
    active: true,
    businessIds: ["biz_gambia"],
  },
];

export const deliveryZones: DeliveryZone[] = [
  { id: "z1", name: "Serrekunda / Senegambia", country: "Gambie", city: "Kanifing", defaultDeliveryFee: 150 },
  { id: "z2", name: "Banjul City", country: "Gambie", city: "Banjul", defaultDeliveryFee: 150 },
  { id: "z3", name: "Bakau / Fajara", country: "Gambie", city: "Kanifing", defaultDeliveryFee: 150 },
  { id: "z4", name: "Kotu / Kololi", country: "Gambie", city: "Kanifing", defaultDeliveryFee: 150 },
  { id: "z5", name: "Brusubi / Bijilo / Sukuta", country: "Gambie", city: "West Coast", defaultDeliveryFee: 150 },
  { id: "z6", name: "Brikama / Lamin", country: "Gambie", city: "West Coast", defaultDeliveryFee: 200 },
  { id: "z7", name: "Tabokoto / Abuko", country: "Gambie", city: "Kanifing", defaultDeliveryFee: 150 },
  { id: "z8", name: "Wellingara / Coastal Road", country: "Gambie", city: "West Coast", defaultDeliveryFee: 200 },
];

export const initialProducts: Product[] = [
  {
    id: "prod_watch_ultra",
    businessId: "biz_gambia",
    name: "Montre Connectée Ultra Pro Max (Série 9)",
    sku: "WATCH-ULTRA-01",
    salePrice: 1800,
    costPrice: 650,
    alertThreshold: 10,
    currentStock: 35,
    reservedStock: 6,
    active: true,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&auto=format&fit=crop&q=60",
  },
  {
    id: "prod_laser_crystal",
    businessId: "biz_gambia",
    name: "Épilateur Laser Crystal IPL Sans Douleur",
    sku: "EPI-CRYSTAL-02",
    salePrice: 1400,
    costPrice: 500,
    alertThreshold: 8,
    currentStock: 4, // Alerte stock bas
    reservedStock: 3,
    active: true,
    image: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=500&auto=format&fit=crop&q=60",
  },
  {
    id: "prod_clipper_vgr",
    businessId: "biz_gambia",
    name: "Tondeuse Professionnelle Barbe & Cheveux VGR",
    sku: "TOND-VGR-03",
    salePrice: 1100,
    costPrice: 400,
    alertThreshold: 15,
    currentStock: 42,
    reservedStock: 4,
    active: true,
    image: "https://images.unsplash.com/photo-1621607512214-68297480165e?w=500&auto=format&fit=crop&q=60",
  },
  {
    id: "prod_serum_pack",
    businessId: "biz_gambia",
    name: "Pack Sérum Vitamine C + Crème Anti-Taches",
    sku: "SKIN-SERUM-04",
    salePrice: 850,
    costPrice: 280,
    alertThreshold: 10,
    currentStock: 18,
    reservedStock: 4,
    active: true,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500&auto=format&fit=crop&q=60",
  },
  {
    id: "prod_mini_proj",
    businessId: "biz_gambia",
    name: "Mini Projecteur Vidéo HD Portatif 4K",
    sku: "PROJ-MINI-05",
    salePrice: 3200,
    costPrice: 1200,
    alertThreshold: 5,
    currentStock: 2, // Alerte stock critique
    reservedStock: 2,
    active: true,
    image: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=500&auto=format&fit=crop&q=60",
  },
  {
    id: "prod_airpods_pro",
    businessId: "biz_gambia",
    name: "Écouteurs Sans Fil Pro ANC avec Boîtier",
    sku: "EAR-PRO-06",
    salePrice: 950,
    costPrice: 320,
    alertThreshold: 8,
    currentStock: 24,
    reservedStock: 3,
    active: true,
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500&auto=format&fit=crop&q=60",
  },
];

export const initialOrders: Order[] = [
  {
    id: "ord_001",
    businessId: "biz_gambia",
    orderNumber: "CMD-GM-101",
    customerName: "Fatou Ceesay",
    customerPhone: "+2203112233",
    deliveryAddress: "Kairaba Avenue, opposite Stop Step Pharmacy",
    zone: "Serrekunda / Senegambia",
    source: "Facebook Ads",
    status: "DELIVERED",
    totalAmount: 1950, // 1800 + 150
    deliveryFee: 150,
    deliveryAgentId: "user_rider_gambia",
    confirmerId: "user_confirmer_1",
    deliveredAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    items: [
      {
        id: "item_001",
        productId: "prod_watch_ultra",
        productName: "Montre Connectée Ultra Pro Max (Série 9)",
        quantity: 1,
        unitPrice: 1800,
        frozenCostPrice: 650,
      },
    ],
    statusHistory: [
      {
        id: "h_001",
        toStatus: "NEW",
        changedById: "user_mouhamed",
        changedByName: "Système Webhook",
        createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
      },
      {
        id: "h_002",
        fromStatus: "NEW",
        toStatus: "CONFIRMED",
        changedById: "user_confirmer_1",
        changedByName: "Fatoumatta Bah",
        note: "Client joint au téléphone, confirmation OK pour Kairaba Ave",
        createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
      },
      {
        id: "h_003",
        fromStatus: "CONFIRMED",
        toStatus: "IN_DELIVERY",
        changedById: "user_rider_gambia",
        changedByName: "Bakary Touray",
        note: "Prise en charge par le livreur",
        createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
      },
      {
        id: "h_004",
        fromStatus: "IN_DELIVERY",
        toStatus: "DELIVERED",
        changedById: "user_rider_gambia",
        changedByName: "Bakary Touray",
        note: "Encaissé 1 950 GMD en espèces",
        createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
      },
    ],
  },
  {
    id: "ord_002",
    businessId: "biz_gambia",
    orderNumber: "CMD-GM-102",
    customerName: "Lamin Jammeh",
    customerPhone: "+2207014455",
    deliveryAddress: "Westfield junction, near Elton Petrol Station",
    zone: "Serrekunda / Senegambia",
    source: "TikTok Ads",
    status: "IN_DELIVERY",
    totalAmount: 1250, // 1100 + 150
    deliveryFee: 150,
    deliveryAgentId: "user_rider_gambia",
    confirmerId: "user_confirmer_1",
    createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    items: [
      {
        id: "item_002",
        productId: "prod_clipper_vgr",
        productName: "Tondeuse Professionnelle Barbe & Cheveux VGR",
        quantity: 1,
        unitPrice: 1100,
        frozenCostPrice: 400,
      },
    ],
    statusHistory: [
      {
        id: "h_005",
        toStatus: "NEW",
        changedById: "user_mouhamed",
        changedByName: "Système",
        createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
      },
      {
        id: "h_006",
        fromStatus: "NEW",
        toStatus: "CONFIRMED",
        changedById: "user_confirmer_1",
        changedByName: "Fatoumatta Bah",
        createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
      },
      {
        id: "h_007",
        fromStatus: "CONFIRMED",
        toStatus: "IN_DELIVERY",
        changedById: "user_rider_gambia",
        changedByName: "Bakary Touray",
        note: "En cours de livraison à Westfield",
        createdAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
      },
    ],
  },
  {
    id: "ord_003",
    businessId: "biz_gambia",
    orderNumber: "CMD-GM-103",
    customerName: "Mariama Jallow",
    customerPhone: "+2209988112",
    deliveryAddress: "Banjul Marina Parade, near State House",
    zone: "Banjul City",
    source: "Facebook Ads",
    status: "FAILED",
    failReason: "Client injoignable (3 tentatives sans réponse)",
    totalAmount: 1550, // 1400 + 150
    deliveryFee: 150,
    deliveryAgentId: "user_rider_gambia",
    confirmerId: "user_confirmer_1",
    createdAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    items: [
      {
        id: "item_003",
        productId: "prod_laser_crystal",
        productName: "Épilateur Laser Crystal IPL Sans Douleur",
        quantity: 1,
        unitPrice: 1400,
        frozenCostPrice: 500,
      },
    ],
    statusHistory: [
      {
        id: "h_008",
        toStatus: "NEW",
        changedById: "user_mouhamed",
        changedByName: "Système",
        createdAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
      },
      {
        id: "h_009",
        fromStatus: "NEW",
        toStatus: "CONFIRMED",
        changedById: "user_confirmer_1",
        changedByName: "Fatoumatta Bah",
        createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
      },
      {
        id: "h_010",
        fromStatus: "CONFIRMED",
        toStatus: "FAILED",
        changedById: "user_rider_gambia",
        changedByName: "Bakary Touray",
        note: "Téléphone sonne dans le vide, injoignable sur WhatsApp",
        createdAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
      },
    ],
  },
  {
    id: "ord_004",
    businessId: "biz_gambia",
    orderNumber: "CMD-GM-104",
    customerName: "Modou Faye",
    customerPhone: "+2202233445",
    deliveryAddress: "Brusubi Roundabout, Phase 2, Villa 12",
    zone: "Brusubi / Bijilo / Sukuta",
    source: "Facebook Ads",
    status: "DELIVERED",
    totalAmount: 1000, // 850 + 150
    deliveryFee: 150,
    deliveryAgentId: "user_rider_gambia",
    confirmerId: "user_confirmer_1",
    deliveredAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    items: [
      {
        id: "item_004",
        productId: "prod_serum_pack",
        productName: "Pack Sérum Vitamine C + Crème Anti-Taches",
        quantity: 1,
        unitPrice: 850,
        frozenCostPrice: 280,
      },
    ],
    statusHistory: [
      {
        id: "h_011",
        toStatus: "DELIVERED",
        changedById: "user_rider_gambia",
        changedByName: "Bakary Touray",
        note: "Payé en espèces 1 000 GMD",
        createdAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
      },
    ],
  },
  {
    id: "ord_005",
    businessId: "biz_gambia",
    orderNumber: "CMD-GM-105",
    customerName: "Isatou Sowe",
    customerPhone: "+2203994488",
    deliveryAddress: "Brikama Market Road, near Central Mosque",
    zone: "Brikama / Lamin",
    source: "WhatsApp",
    status: "NEW",
    totalAmount: 3400, // 3200 + 200
    deliveryFee: 200,
    createdAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    items: [
      {
        id: "item_005",
        productId: "prod_mini_proj",
        productName: "Mini Projecteur Vidéo HD Portatif 4K",
        quantity: 1,
        unitPrice: 3200,
        frozenCostPrice: 1200,
      },
    ],
    statusHistory: [
      {
        id: "h_012",
        toStatus: "NEW",
        changedById: "user_partner",
        changedByName: "Associé Gambie",
        createdAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
      },
    ],
  },
];

export const initialExpenses: Expense[] = [
  {
    id: "exp_001",
    businessId: "biz_gambia",
    date: new Date().toISOString(),
    category: "ADS_FACEBOOK",
    amount: 750,
    paymentMethod: "Carte Bancaire",
    note: "Budget pub Facebook (Campagne Montre Ultra Série 9 Banjul)",
    adPlatform: "Facebook Ads",
    campaignName: "WATCH-ULTRA-GM-PROMO",
  },
  {
    id: "exp_002",
    businessId: "biz_gambia",
    date: new Date().toISOString(),
    category: "ADS_TIKTOK",
    amount: 550,
    paymentMethod: "Carte Bancaire",
    note: "Campagne TikTok Ads Tondeuse VGR Gambie",
    adPlatform: "TikTok Ads",
    campaignName: "TIKTOK-VGR-GM-01",
  },
  {
    id: "exp_003",
    businessId: "biz_gambia",
    date: new Date().toISOString(),
    category: "SHIPPING_LOGISTICS",
    amount: 250,
    paymentMethod: "Wave",
    note: "Carburant moto livreur Bakary Touray (Serrekunda)",
  },
  {
    id: "exp_004",
    businessId: "biz_gambia",
    date: new Date().toISOString(),
    category: "SALARY_COMMISSION",
    amount: 300,
    paymentMethod: "Espèces",
    note: "Commission livraisons du jour Bakary Touray",
  },
];

export const initialRemittances: CashRemittance[] = [
  {
    id: "rem_001",
    deliveryAgentId: "user_rider_gambia",
    deliveryAgentName: "Bakary Touray (Livreur Banjul / Kairaba)",
    businessId: "biz_gambia",
    date: new Date().toISOString(),
    expectedAmount: 2950, // Commandes ord_001 (1950) + ord_004 (1000)
    remittedAmount: 2950,
    discrepancy: 0,
    status: "VERIFIED",
    verifiedById: "user_mouhamed",
    notes: "Remis en espèces au bureau à Serrekunda",
    orderIds: ["ord_001", "ord_004"],
  },
];

export const initialDailyNotes: DailyProblemNote[] = [
  {
    id: "note_001",
    text: "Livreur Bakary : fort ralentissement à Westfield, 2 clients contactés pour décaler à 15h30.",
    category: "LOGISTICS",
    resolved: false,
    createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
  },
  {
    id: "note_002",
    text: "Stock Mini Projecteur critique (reste 2 unités). Confirmer le nouvel arrivage avec le transitaire.",
    category: "STOCK",
    resolved: false,
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
  },
];
